name: Manual Stats Update

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual update'
        required: false
        default: 'Manual trigger'

permissions:
  contents: write
  actions: read

jobs:
  manual-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Update GitHub Stats
      run: |
        python scripts/dynamic_stats.py
        
    - name: Update README with latest stats
      run: |
        python scripts/update_readme.py
        
    - name: Get current date
      id: date
      run: echo "date=$(date)" >> $GITHUB_OUTPUT
        
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: '🔄 Manual stats update - ${{ github.event.inputs.reason }} - ${{ steps.date.outputs.date }}'
        branch: main
        commit_user_name: github-actions[bot]
        commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
        commit_author: GitHub Actions <actions@github.com>
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}